/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;


import java.awt.Color;
import java.awt.Component;
import java.awt.GradientPaint;
import java.awt.Image;
import javax.swing.JLabel;
import logic.Facade;
/**
 *
 * @author s2-martyr
 */
public class Frame extends javax.swing.JFrame {
  private Facade game = new Facade();
  private boolean gameOver = false;
 
    /**
     * Creates new form AgentFrame
     */
    public Frame() {
        initComponents();   
        setLocation(100, 100);
        setSize(700, 600);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    controlPanel = new javax.swing.JPanel();
    scorePanel = new javax.swing.JPanel();
    playerOne = new javax.swing.JLabel();
    scoreOne = new javax.swing.JLabel();
    playerTwo = new javax.swing.JLabel();
    scoreTwo = new javax.swing.JLabel();
    emptyPanel = new javax.swing.JPanel();
    newButtonPanel = new javax.swing.JPanel();
    newGame = new javax.swing.JButton();
    gamePanel = new javax.swing.JPanel();
    grid11 = new javax.swing.JLabel();
    grid12 = new javax.swing.JLabel();
    grid13 = new javax.swing.JLabel();
    grid21 = new javax.swing.JLabel();
    grid22 = new javax.swing.JLabel();
    grid23 = new javax.swing.JLabel();
    grid31 = new javax.swing.JLabel();
    grid32 = new javax.swing.JLabel();
    grid33 = new javax.swing.JLabel();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("Agent Frame");

    controlPanel.setLayout(new java.awt.BorderLayout());

    scorePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Scores:"));
    scorePanel.setLayout(new java.awt.GridLayout(2, 2));

    playerOne.setText("Player 1:");
    scorePanel.add(playerOne);

    scoreOne.setText("0");
    scorePanel.add(scoreOne);

    playerTwo.setText("Player 2:");
    scorePanel.add(playerTwo);

    scoreTwo.setText("0");
    scorePanel.add(scoreTwo);

    controlPanel.add(scorePanel, java.awt.BorderLayout.NORTH);

    javax.swing.GroupLayout emptyPanelLayout = new javax.swing.GroupLayout(emptyPanel);
    emptyPanel.setLayout(emptyPanelLayout);
    emptyPanelLayout.setHorizontalGroup(
      emptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 119, Short.MAX_VALUE)
    );
    emptyPanelLayout.setVerticalGroup(
      emptyPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGap(0, 233, Short.MAX_VALUE)
    );

    controlPanel.add(emptyPanel, java.awt.BorderLayout.CENTER);

    newGame.setText("New Game");
    newGame.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        newGameMouseClicked(evt);
      }
    });

    javax.swing.GroupLayout newButtonPanelLayout = new javax.swing.GroupLayout(newButtonPanel);
    newButtonPanel.setLayout(newButtonPanelLayout);
    newButtonPanelLayout.setHorizontalGroup(
      newButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(newButtonPanelLayout.createSequentialGroup()
        .addContainerGap()
        .addComponent(newGame)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );
    newButtonPanelLayout.setVerticalGroup(
      newButtonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newButtonPanelLayout.createSequentialGroup()
        .addContainerGap(40, Short.MAX_VALUE)
        .addComponent(newGame)
        .addGap(37, 37, 37))
    );

    controlPanel.add(newButtonPanel, java.awt.BorderLayout.SOUTH);

    getContentPane().add(controlPanel, java.awt.BorderLayout.EAST);

    gamePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    gamePanel.setLayout(new java.awt.GridLayout(3, 3));

    grid11.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    grid11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    grid11.setText(" ");
    grid11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    grid11.setName("grid11"); // NOI18N
    grid11.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        grid11MouseClicked(evt);
      }
    });
    gamePanel.add(grid11);

    grid12.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    grid12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    grid12.setText(" ");
    grid12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    grid12.setName("grid12"); // NOI18N
    grid12.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        grid11MouseClicked(evt);
      }
    });
    gamePanel.add(grid12);

    grid13.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    grid13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    grid13.setText(" ");
    grid13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    grid13.setName("grid13"); // NOI18N
    grid13.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        grid11MouseClicked(evt);
      }
    });
    gamePanel.add(grid13);

    grid21.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    grid21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    grid21.setText(" ");
    grid21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    grid21.setName("grid21"); // NOI18N
    grid21.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        grid11MouseClicked(evt);
      }
    });
    gamePanel.add(grid21);

    grid22.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    grid22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    grid22.setText(" ");
    grid22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    grid22.setName("grid22"); // NOI18N
    grid22.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        grid11MouseClicked(evt);
      }
    });
    gamePanel.add(grid22);

    grid23.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    grid23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    grid23.setText(" ");
    grid23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    grid23.setName("grid23"); // NOI18N
    grid23.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        grid11MouseClicked(evt);
      }
    });
    gamePanel.add(grid23);

    grid31.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    grid31.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    grid31.setText(" ");
    grid31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    grid31.setName("grid31"); // NOI18N
    grid31.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        grid11MouseClicked(evt);
      }
    });
    gamePanel.add(grid31);

    grid32.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    grid32.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    grid32.setText(" ");
    grid32.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    grid32.setName("grid32"); // NOI18N
    grid32.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        grid11MouseClicked(evt);
      }
    });
    gamePanel.add(grid32);

    grid33.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
    grid33.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    grid33.setText(" ");
    grid33.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
    grid33.setName("grid33"); // NOI18N
    grid33.addMouseListener(new java.awt.event.MouseAdapter() {
      public void mouseClicked(java.awt.event.MouseEvent evt) {
        grid11MouseClicked(evt);
      }
    });
    gamePanel.add(grid33);

    getContentPane().add(gamePanel, java.awt.BorderLayout.CENTER);

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void grid11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grid11MouseClicked
      Component c = evt.getComponent();
      if (c instanceof JLabel){ //check we have a JLabel
        if( " ".equals(((JLabel)c).getText()) && gameOver != true){ // check the Jlabel is empty
          if(game.makeMove(((JLabel)c).getName())){
            ((JLabel)c).setText("X");
          }
        }
        else
        {
          return;
        }
      }
      gameOver(true);
      if(gameOver != true){
        agentTurn();
        gameOver(false);
      }
    }//GEN-LAST:event_grid11MouseClicked

    private void agentTurn(){
      int[] location = new int[2];
            location = game.agentsMove();
      handleGridMouseClick(location[0], location[1]);
    }
    
    private void handleGridMouseClick( int row, int column )
    {       
      // perform the human move
      JLabel label = getLabel( row + 1, column + 1 );
             label.setText( "0" );
             // fire the rules to see if game is over (won/drawn)
      }                 
    
    private JLabel getLabel(int row, int column){
      JLabel location = null;
      String match = "grid" + Integer.toString(row) + Integer.toString(column); 
      int length = gamePanel.getComponents().length;
      Component[] cells = new Component[length];
      cells = gamePanel.getComponents();
      for(int i = 0; i < length; i++){
       if(((JLabel)cells[i]).getName().equals(match)){
         location = ((JLabel)cells[i]);
       }
      }
      return location; 
    }
    
    private void newGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newGameMouseClicked
     newGame();

    }//GEN-LAST:event_newGameMouseClicked

    private void newGame() {
     game.newGame();
     gameOver = false;
     int comps =  gamePanel.getComponents().length;
     for(int i = 0; i < comps; i++ )
     {
      Component toChange =  gamePanel.getComponent(i);
      ((JLabel)toChange).setText(" ");
      
     }
    }
    
    private void gameOver(boolean winner){
      int store;
      if(game.gameOver()){
        if(game.win()){
          if(winner){
            store = Integer.parseInt(scoreOne.getText());
            store++;
            scoreOne.setText(Integer.toString(store));
          }
          else
          {
            store = Integer.parseInt(scoreTwo.getText());
            store++;
            scoreTwo.setText(Integer.toString(store));
          }
        }
        gameOver = true;
      }
      else
      {
        gameOver = false;
      }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Frame().setVisible(true);
                
            }
        });
    }
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JPanel controlPanel;
  private javax.swing.JPanel emptyPanel;
  private javax.swing.JPanel gamePanel;
  private javax.swing.JLabel grid11;
  private javax.swing.JLabel grid12;
  private javax.swing.JLabel grid13;
  private javax.swing.JLabel grid21;
  private javax.swing.JLabel grid22;
  private javax.swing.JLabel grid23;
  private javax.swing.JLabel grid31;
  private javax.swing.JLabel grid32;
  private javax.swing.JLabel grid33;
  private javax.swing.JPanel newButtonPanel;
  private javax.swing.JButton newGame;
  private javax.swing.JLabel playerOne;
  private javax.swing.JLabel playerTwo;
  private javax.swing.JLabel scoreOne;
  private javax.swing.JPanel scorePanel;
  private javax.swing.JLabel scoreTwo;
  // End of variables declaration//GEN-END:variables
}
